# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userinfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=200)),
                ('is_active', models.BooleanField()),
                ('privilege', models.CharField(max_length=100)),
            ],
        ),
    ]
