# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-13 03:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabinet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cabinet', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='MachineRoom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('macroom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
                ('role', models.CharField(max_length=50)),
                ('hardwareinfo', models.CharField(max_length=200)),
                ('gameinfo', models.CharField(max_length=300)),
                ('cb', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.Cabinet')),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assets_management.MachineRoom')),
            ],
        ),
        migrations.AddField(
            model_name='cabinet',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assets_management.MachineRoom'),
        ),
    ]
